name: Install Server
description: 'Installs the ownCloud server for testing purposes'

inputs:
  db-docker-image:
    description: 'Database docker image which is used (e.g. sqlite, mysql:8.0)'
    required: true

runs:
  using: composite
  steps:
    - name: Install Composer dependencies
      shell: bash
      run: |
        make install-composer-deps
        make vendor-bin-deps

    - name: Install Server
      shell: bash
      env:
        DATA_DIRECTORY: ${{ github.workspace }}/data
        DB: ${{ inputs.db-docker-image }}
        DB_NAME: owncloud
        ADMIN_LOGIN: admin
        ADMIN_PASSWORD: admin
        DB_HOST: 127.0.0.1
        DB_USERNAME: owncloud
        DB_PASSWORD: owncloud

      run: |
        DB_TYPE=${DB%:*}
        if [ $DB_TYPE == "postgres" ] ; then DB_TYPE="pgsql"; fi
        if [ $DB_TYPE == "mariadb" ] ; then DB_TYPE="mysql"; fi
        install_cmd="maintenance:install -vvv \
          --database=${DB_TYPE} \
          --database-name=${DB_NAME} \
          --admin-user=${ADMIN_LOGIN} \
          --admin-pass=${ADMIN_PASSWORD} \
          --data-dir=${DATA_DIRECTORY} "
        
        if [[ "${DB_TYPE}" != "sqlite" ]]; then
          install_cmd+=" --database-host=${DB_HOST} \
            --database-user=${DB_USERNAME} \
            --database-pass=${DB_PASSWORD}"
        fi
        
        php occ ${install_cmd}
        echo "enabling apps"
        php occ app:enable files_sharing
        php occ app:enable files_trashbin
        php occ app:enable files_versions
        php occ app:enable provisioning_api
        php occ app:enable federation
        php occ app:enable federatedfilesharing
