on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the app'
        required: true
        type: string
      php-versions:
        description: JSON array of PHP versions
        required: true
        type: string
      core-ref:
        description: 'git reference to checkout for core'
        required: false
        type: string
        default: ''
      core-ref-php74:
        description: 'git reference to checkout for core if PHP 7.4 is used'
        required: false
        type: string
        default: ''
      app-repository:
        description: 'Repository of the app (optional, defaults to the current repository)'
        required: false
        type: string
        default: ''
      do-integration-tests:
        description: 'Whether to run PHP integration tests'
        required: false
        type: boolean
        default: false
      additional-app:
        description: 'Additional app to enable for testing'
        required: false
        type: string
        default: ''
      additional-app-github-token:
        description: 'GitHub PAT to access the additional app repo - required if private'
        required: false
        type: string
        default: ''
      additional-packages:
        description: Additional Linux packages to be installed - space separated
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}
        database: [sqlite]
        include:
          - php: ${{ fromJSON(inputs.php-versions)[0] }}
            database: "mysql:8.0"
          - php: ${{ fromJSON(inputs.php-versions)[0] }}
            database: "mariadb:10.6"
          - php: ${{ fromJSON(inputs.php-versions)[0] }}
            database: "postgres:10.21"

    services:
      mysql:
        image: >-
          ${{ (startsWith(matrix.database,'mysql:') || startsWith(matrix.database,'mariadb:')) && matrix.database || '' }}
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: owncloud
          MYSQL_USER: owncloud
          MYSQL_PASSWORD: owncloud
        options: >-
          --health-cmd="mysqladmin ping -u root -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
      postgres:
        image: ${{ startsWith(matrix.database,'postgres:') && matrix.database || '' }}
        env:
          POSTGRES_DB: owncloud
          POSTGRES_USER: owncloud
          POSTGRES_PASSWORD: owncloud
        ports:
          - 5432:5432

    steps:
      - name: Setup ownCloud environment
        uses: ./.github/actions/setup-owncloud-env
        with:
          app-name: ${{ inputs.app-name }}
          app-repository: ${{ inputs.app-repository }}
          core-ref: ${{ inputs.core-ref }}
          core-ref-php74: ${{ inputs.core-ref-php74 }}
          php-version: ${{ matrix.php }}
          additional-app: ${{ inputs.additional-app }}
          additional-app-github-token: ${{ inputs.additional-app-github-token }}

      - name: Setup PHP and server
        uses: ./.github/actions/setup-php-server
        with:
          php-version: ${{ matrix.php }}
          additional-packages: ${{ inputs.additional-packages }}
          database: ${{ matrix.database }}

      - name: Setup additional app
        if: ${{ inputs.additional-app != '' }}
        env:
          ADDITIONAL_APP: ${{ inputs.additional-app }}
        run: |
          ( cd "apps/${ADDITIONAL_APP}" && make vendor || true)
          php occ a:e "${ADDITIONAL_APP}"

      - name: Setup app
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          ( cd "apps/${APP_NAME}" && make vendor || true)
          php occ a:e "${APP_NAME}"

      - name: Run PHPUnit
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          cd "apps/${APP_NAME}"
          make test-php-unit

      - name: Run PHP Integration tests
        if: ${{ inputs.do-integration-tests }}
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          cd "apps/${APP_NAME}"
          make test-php-integration

      - name: Tail log
        if: always()
        run: |
          ls -la data
          cat data/owncloud.log
