on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the app'
        required: true
        type: string
      php-versions:
        description: JSON array of PHP versions
        required: true
        type: string
      core-ref:
        description: 'git reference to checkout for core'
        required: false
        type: string
        default: ''
      core-ref-php74:
        description: 'git reference to checkout for core if PHP 7.4 is used'
        required: false
        type: string
        default: ''
      app-repository:
        description: 'Repository of the app (optional, defaults to the current repository)'
        required: false
        type: string
        default: ''
      disable-phpstan:
        description: 'Whether to disable PHPStan checks'
        required: false
        type: boolean
        default: false
      disable-phan:
        description: 'Whether to disable Phan checks'
        required: false
        type: boolean
        default: false
      additional-app:
        description: 'Additional app to enable for testing'
        required: false
        type: string
        default: ''
      additional-app-github-token:
        description: 'GitHub PAT to access the additional app repo - required if private'
        required: false
        type: string
        default: ''
      additional-packages:
        description: Additional Linux packages to be installed - space separated
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  php-codestyle:
    name: PHP Code Style
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}

    steps:
      - name: Setup ownCloud environment
        uses: ./.github/actions/setup-owncloud-env
        with:
          app-name: ${{ inputs.app-name }}
          app-repository: ${{ inputs.app-repository }}
          core-ref: ${{ inputs.core-ref }}
          core-ref-php74: ${{ inputs.core-ref-php74 }}
          php-version: ${{ matrix.php }}
          additional-app: ${{ inputs.additional-app }}
          additional-app-github-token: ${{ inputs.additional-app-github-token }}

      - name: Setup PHP and server
        uses: ./.github/actions/setup-php-server
        with:
          php-version: ${{ matrix.php }}
          additional-packages: ${{ inputs.additional-packages }}

      - name: Setup additional app
        if: ${{ inputs.additional-app != '' }}
        env:
          ADDITIONAL_APP: ${{ inputs.additional-app }}
        run: |
          ( cd "apps/${ADDITIONAL_APP}" && make vendor || true)
          php occ a:e "${ADDITIONAL_APP}"

      - name: Setup app
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          ( cd "apps/${APP_NAME}" && make vendor || true)
          php occ a:e "${APP_NAME}"

      - name: Run PHP Code Style Checks
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          cd "apps/${APP_NAME}"
          make test-php-style

      - name: Run PHP Stan
        if: ${{ !inputs.disable-phpstan }}
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          cd "apps/${APP_NAME}"
          make test-php-phpstan

      - name: Run PHP Phan
        if: ${{ !inputs.disable-phan }}
        env:
          APP_NAME: ${{ inputs.app-name }}
        run: |
          cd "apps/${APP_NAME}"
          make test-php-phan
