name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  semantic-git-messages:
    name: Commits
    uses: ./.github/workflows/semantic-git-message.yml

  php-code-style:
    name: PHP Code Style
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'

  php-code-style-no-phan:
    name: PHP Code Style (--no-phan)
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'
      disable-phan: true

  php-code-style-additional-app:
    name: PHP Code Style (+additional app)
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'
      additional-app: customgroups

  php-unit:
    name: PHP Unit
    uses: ./.github/workflows/php-unit.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'

  php-integration:
    name: PHP Integration
    uses: ./.github/workflows/php-unit.yml
    with:
      app-name: notes
      app-repository: owncloud/notes
      php-versions: '["8.3"]'
      do-integration-tests: true

  js-unit:
    name: JS Unit
    uses: ./.github/workflows/js-unit.yml
    with:
      app-name: customgroups
      app-repository: owncloud/customgroups
      php-version: '8.3'
      additional-packages: exiftool bison
