name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  semantic-git-messages:
    name: Commits
    uses: ./.github/workflows/semantic-git-message.yml

  php-code-style:
    name: PHP Code Style
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'

  php-code-style-no-phan:
    name: PHP Code Style (--no-phan)
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'
      disable-phan: true

  php-code-style-additional-app:
    name: PHP Code Style (+additional app)
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'
      additional-app: customgroups

  php-unit:
    name: PHP Unit
    uses: ./.github/workflows/php-unit.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      php-versions: '["8.3"]'

  php-integration:
    name: PHP Integration
    uses: ./.github/workflows/php-unit.yml
    with:
      app-name: notes
      app-repository: owncloud/notes
      php-versions: '["8.3"]'
      do-integration-tests: true

  js-unit:
    name: JS Unit
    uses: ./.github/workflows/js-unit.yml
    with:
      app-name: customgroups
      app-repository: owncloud/customgroups
      php-version: '8.3'
      additional-packages: exiftool bison

  js-unit-xvfb-display:
    name: JS Unit with Xvfb Display Server
    uses: ./.github/workflows/js-unit.yml
    with:
      app-name: calendar
      app-repository: owncloud/calendar
      php-version: '8.3'
      enable-xvfb-display-server: true

  build-dist:
    name: Build dist
    uses: ./.github/workflows/build.yml

  calens:
    name: Changelog
    uses: ./.github/workflows/calens.yml
    secrets:
      APP_ID: ${{ secrets.CALENS_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.CALENS_APP_PRIVATE_KEY }}

  acceptance-api:
    name: API acceptance tests
    uses: ./.github/workflows/acceptance.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      do-api-tests: true

  acceptance-webui:
    name: WebUI acceptance tests
    uses: ./.github/workflows/acceptance.yml
    with:
      app-name: impersonate
      app-repository: owncloud/impersonate
      do-webui-tests: true

  acceptance-api-email:
    name: API acceptance tests with Email Server
    uses: ./.github/workflows/acceptance.yml
    with:
      app-name: notifications
      app-repository: owncloud/notifications
      do-api-tests: true
      use-email-server: true
